        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:28:27 2014
        MODULE XERBLA__genmod
          INTERFACE 
            SUBROUTINE XERBLA(SRNAME,INFO)
              CHARACTER(LEN=6) :: SRNAME
              INTEGER(KIND=4) :: INFO
            END SUBROUTINE XERBLA
          END INTERFACE 
        END MODULE XERBLA__genmod
