        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:58 2014
        MODULE CHECKINCREMENTS__genmod
          INTERFACE 
            SUBROUTINE CHECKINCREMENTS(INFO)
              INTEGER(KIND=4), INTENT(OUT) :: INFO
            END SUBROUTINE CHECKINCREMENTS
          END INTERFACE 
        END MODULE CHECKINCREMENTS__genmod
