        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:58 2014
        MODULE CURRENT2PREVIOUSITERATION__genmod
          INTERFACE 
            SUBROUTINE CURRENT2PREVIOUSITERATION
            END SUBROUTINE CURRENT2PREVIOUSITERATION
          END INTERFACE 
        END MODULE CURRENT2PREVIOUSITERATION__genmod
