        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:58 2014
        MODULE CURRENT2PREVIOUSTIMESTEP__genmod
          INTERFACE 
            SUBROUTINE CURRENT2PREVIOUSTIMESTEP
            END SUBROUTINE CURRENT2PREVIOUSTIMESTEP
          END INTERFACE 
        END MODULE CURRENT2PREVIOUSTIMESTEP__genmod
