        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:59 2014
        MODULE INITIALGUESS__genmod
          INTERFACE 
            SUBROUTINE INITIALGUESS
            END SUBROUTINE INITIALGUESS
          END INTERFACE 
        END MODULE INITIALGUESS__genmod
