        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:58 2014
        MODULE PREVIOUS2CURRENT__genmod
          INTERFACE 
            SUBROUTINE PREVIOUS2CURRENT
            END SUBROUTINE PREVIOUS2CURRENT
          END INTERFACE 
        END MODULE PREVIOUS2CURRENT__genmod
