        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:58 2014
        MODULE REDUCETIMESTEP__genmod
          INTERFACE 
            SUBROUTINE REDUCETIMESTEP
            END SUBROUTINE REDUCETIMESTEP
          END INTERFACE 
        END MODULE REDUCETIMESTEP__genmod
