        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:59 2014
        MODULE SETEQUATIONCOEFFICIENTS__genmod
          INTERFACE 
            SUBROUTINE SETEQUATIONCOEFFICIENTS
            END SUBROUTINE SETEQUATIONCOEFFICIENTS
          END INTERFACE 
        END MODULE SETEQUATIONCOEFFICIENTS__genmod
