        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:40:00 2014
        MODULE SETINITIALVALUES__genmod
          INTERFACE 
            SUBROUTINE SETINITIALVALUES
              USE SOLVER_2D
            END SUBROUTINE SETINITIALVALUES
          END INTERFACE 
        END MODULE SETINITIALVALUES__genmod
