        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:58 2014
        MODULE SETLIQGASPARMS__genmod
          INTERFACE 
            SUBROUTINE SETLIQGASPARMS
            END SUBROUTINE SETLIQGASPARMS
          END INTERFACE 
        END MODULE SETLIQGASPARMS__genmod
