        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:58 2014
        MODULE SOLVEFORHYDROGEN__genmod
          INTERFACE 
            SUBROUTINE SOLVEFORHYDROGEN
            END SUBROUTINE SOLVEFORHYDROGEN
          END INTERFACE 
        END MODULE SOLVEFORHYDROGEN__genmod
