        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:59 2014
        MODULE UPDATEVARIABLES__genmod
          INTERFACE 
            SUBROUTINE UPDATEVARIABLES
            END SUBROUTINE UPDATEVARIABLES
          END INTERFACE 
        END MODULE UPDATEVARIABLES__genmod
