        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 20 14:39:58 2014
        MODULE WATERPACK__genmod
          INTERFACE 
            SUBROUTINE WATERPACK
            END SUBROUTINE WATERPACK
          END INTERFACE 
        END MODULE WATERPACK__genmod
